name: unities_helper
description: A library to help you convert unities and a few other things
version: 3.0.0
repository: https://github.com/bdlukaa/unities_helper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
