name: unities_helper
description: A library to help you convert unities and a few other things
version: 2.0.0
repository: https://github.com/bdlukaa/unities_helper

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
